dist: trusty
sudo: false
language: rust
cache: cargo
rust:
  - stable
  - beta
  - nightly
  - 1.34.2
script:
  - |
      cargo test --verbose;
      cargo test --verbose --no-default-features;
      cargo doc --verbose;
